In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../data/online_retail_II.csv")
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,09-12-2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,09-12-2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,09-12-2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,09-12-2011 12:50,4.95,12680.0,France
541909,581587,POST,POSTAGE,1,09-12-2011 12:50,18.00,12680.0,France

In [5]:
df.shape

(541910, 8)

In [6]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [7]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [8]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64

In [9]:
missing = df.isnull().sum()

missing_percentage = (missing / len(df)) * 100

pd.DataFrame({
    "missing_count": missing,
    "missing_percentage": missing_percentage
})

             missing_count  missing_percentage
Invoice                  0            0.000000
StockCode                0            0.000000
Description           1454            0.268310
Quantity                 0            0.000000
InvoiceDate              0            0.000000
Price                    0            0.000000
Customer ID         135080           24.926648
Country                  0            0.000000

In [10]:
df.duplicated().sum()

np.int64(5268)

In [11]:
df.describe()

            Quantity          Price    Customer ID
count  541910.000000  541910.000000  406830.000000
mean        9.552234       4.611138   15287.684160
std       218.080957      96.759765    1713.603074
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [12]:
(df["Quantity"] < 0).sum()

np.int64(10624)

In [13]:
df.loc[df["Quantity"] < 0, ["Invoice", "StockCode", "Description", "Quantity", "Price"]].head(20)

      Invoice StockCode                          Description  Quantity  Price
141   C536379         D                             Discount        -1  27.50
154   C536383    35004C      SET OF 3 COLOURED  FLYING DUCKS        -1   4.65
235   C536391     22556       PLASTERS IN TIN CIRCUS PARADE        -12   1.65
236   C536391     21984     PACK OF 12 PINK PAISLEY TISSUES        -24   0.29
237   C536391     21983     PACK OF 12 BLUE PAISLEY TISSUES        -24   0.29
238   C536391     21980    PACK OF 12 RED RETROSPOT TISSUES        -24   0.29
239   C536391     21484          CHICK GREY HOT WATER BOTTLE       -12   3.45
240   C536391     22557     PLASTERS IN TIN VINTAGE PAISLEY        -12   1.65
241   C536391     22553               PLASTERS IN TIN SKULLS       -24   1.65
937   C536506     22960             JAM MAKING SET WITH JARS        -6   4.25
1441  C536543     22632            HAND WARMER RED RETROSPOT        -1   2.10
1442  C536543     22355            CHARLOTTE BAG SUKI DESIGN        -2   0.85
1971  C536548     22244           3 HOOK HANGER MAGIC GARDEN        -4   1.95
1972  C536548     22242        5 HOOK HANGER MAGIC TOADSTOOL        -5   1.65
1973  C536548     20914  SET/5 RED RETROSPOT LID GLASS BOWLS        -1   2.95
1974  C536548     22892    SET OF SALT AND PEPPER TOADSTOOLS        -7   1.25
1975  C536548     22654                   DELUXE SEWING KIT         -1   5.95
1976  C536548     22767          TRIPLE PHOTO FRAME CORNICE         -2   9.95
1977  C536548     22333    RETROSPOT PARTY BAG + STICKER SET        -1   1.65
1978  C536548     22245         HOOK, 1 HANGER ,MAGIC GARDEN        -2   0.85

In [14]:
(df["Quantity"] == 0).sum()

np.int64(0)

In [15]:
(df["Price"] < 0).sum()

np.int64(2)

In [16]:
df.loc[df["Price"] < 0, ["Invoice", "StockCode", "Description", "Quantity", "Price"]].head(20)

        Invoice StockCode      Description  Quantity     Price
299983  A563186         B  Adjust bad debt         1 -11062.06
299984  A563187         B  Adjust bad debt         1 -11062.06

In [17]:
(df["Price"] == 0).sum()

np.int64(2515)

In [18]:
df.loc[df["Price"] == 0, ["Invoice", "StockCode", "Description", "Quantity", "Price"]].head(20)

     Invoice StockCode Description  Quantity  Price
622   536414     22139         NaN        56    0.0
1510  536545     21134         NaN         1    0.0
1985  536547     37509         NaN         1    0.0
1986  536546     22145         NaN         1    0.0
2022  536552     20950         NaN         1    0.0
2023  536549    85226A         NaN         1    0.0
2024  536550     85044         NaN         1    0.0
2025  536553     37461         NaN         3    0.0
2026  536554     84670         NaN        23    0.0
2406  536589     21777         NaN       -10    0.0
4347  536764    84952C         NaN       -38    0.0
4348  536765    84952C         NaN        19    0.0
6391  536941     22734      amazon        20    0.0
6392  536942     22139      amazon        15    0.0
7187  536995     35951         NaN        57    0.0
7188  536996     22712         NaN       -20    0.0
7189  536997     22028         NaN       -20    0.0
7190  536998     85067         NaN        -6    0.0
7191  536999     21421         NaN       110    0.0
7192  537000     21414         NaN       -22    0.0

In [19]:
cancellation_mask = df["Invoice"].astype(str).str.startswith("C")

cancellation_mask.sum()

np.int64(9288)

In [20]:
df.loc[
    cancellation_mask,
    ["Invoice", "StockCode", "Description", "Quantity", "Price", "Customer ID"]
].head(20)

,Invoice,StockCode,Description,Quantity,Price,Customer ID
141,C536379,D,Discount,-1,27.50,14527.0
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,4.65,15311.0
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,1.65,17548.0
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,0.29,17548.0
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,0.29,17548.0
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,0.29,17548.0
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,3.45,17548.0
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,1.65,17548.0
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,1.65,17548.0
937,C536506,22960,JAM MAKING SET WITH JARS,-6,4.25,17897.0
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2.10,17841.0
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,0.85,17841.0
1971,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,1.95,12472.0
1972,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,1.65,12472.0
1973,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2.95,12472.0
1974,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,1.25,12472.0
1975,C536548,22654,DELUXE SEWING KIT,-1,5.95,12472.0
1976,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,9.95,12472.0
1977,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,1.65,12472.0
1978,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,0.85,12472.0

In [21]:
df.groupby(
    cancellation_mask
)["Quantity"].agg(["count", "mean", "min", "max"])

          count       mean    min    max
Invoice
False    532622  10.239954  -9600  80995
True       9288 -29.885228 -80995     -1

In [22]:
df[df["Customer ID"].isna()][
    ["Invoice", "StockCode", "Description", "Quantity", "Price", "Country"]
].head(20)

,Invoice,StockCode,Description,Quantity,Price,Country
622,536414,22139,NaN,56,0.00,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2.51,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2.51,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,0.85,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,1.66,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,1.66,United Kingdom
1448,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,2.51,United Kingdom
1449,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,0.43,United Kingdom
1450,536544,21802,CHRISTMAS TREE HEART DECORATION,9,0.43,United Kingdom
1451,536544,21803,CHRISTMAS TREE STAR DECORATION,11,0.43,United Kingdom
1452,536544,21809,CHRISTMAS HANGING TREE WITH BELL,1,2.51,United Kingdom
1453,536544,21810,CHRISTMAS HANGING STAR WITH BELL,3,2.51,United Kingdom
1454,536544,21811,CHRISTMAS HANGING HEART WITH BELL,1,2.51,United Kingdom
1455,536544,21821,GLITTER STAR GARLAND WITH BELLS,1,7.62,United Kingdom
1456,536544,21822,GLITTER CHRISTMAS TREE WITH BELLS,1,4.21,United Kingdom
1457,536544,21823,PAINTED METAL HEART WITH HOLLY BELL,2,2.98,United Kingdom
1458,536544,21844,RED RETROSPOT MUG,2,5.91,United Kingdom
1459,536544,21851,LILAC DIAMANTE PEN IN GIFT BOX,1,4.21,United Kingdom
1460,536544,21870,I CAN ONLY PLEASE ONE PERSON MUG,1,3.36,United Kingdom
1461,536544,21871,SAVE THE PLANET MUG,5,3.36,United Kingdom

In [23]:
df[df["Customer ID"].isna()]["Country"].value_counts().head(10)

Country
United Kingdom    133600
EIRE                 711
Hong Kong            288
Unspecified          202
Switzerland          125
France                66
Israel                47
Portugal              39
Bahrain                2
Name: count, dtype: int64

In [24]:
df[df["Description"].isna()][
    ["Invoice", "StockCode", "Quantity", "Price", "Customer ID", "Country"]
].head(20)

     Invoice StockCode  Quantity  Price  Customer ID         Country
622   536414     22139        56    0.0          NaN  United Kingdom
1510  536545     21134         1    0.0          NaN  United Kingdom
1985  536547     37509         1    0.0          NaN  United Kingdom
1986  536546     22145         1    0.0          NaN  United Kingdom
2022  536552     20950         1    0.0          NaN  United Kingdom
2023  536549    85226A         1    0.0          NaN  United Kingdom
2024  536550     85044         1    0.0          NaN  United Kingdom
2025  536553     37461         3    0.0          NaN  United Kingdom
2026  536554     84670        23    0.0          NaN  United Kingdom
2406  536589     21777       -10    0.0          NaN  United Kingdom
4347  536764    84952C       -38    0.0          NaN  United Kingdom
4348  536765    84952C        19    0.0          NaN  United Kingdom
7187  536995     35951        57    0.0          NaN  United Kingdom
7188  536996     22712       -20    0.0          NaN  United Kingdom
7189  536997     22028       -20    0.0          NaN  United Kingdom
7190  536998     85067        -6    0.0          NaN  United Kingdom
7191  536999     21421       110    0.0          NaN  United Kingdom
7192  537000     21414       -22    0.0          NaN  United Kingdom
7193  537001     21653        -6    0.0          NaN  United Kingdom
7194  537002     21651        70    0.0          NaN  United Kingdom

In [25]:
df["Invoice"].nunique()

25900

In [26]:
df.groupby("StockCode")["Quantity"].sum().sort_values(
    ascending=False
).head(10)

StockCode
22197     56450
84077     53847
85099B    47363
85123A    38830
84879     36221
21212     36039
23084     30646
22492     26437
22616     26315
21977     24753
Name: Quantity, dtype: int64

In [27]:
df.groupby("Country")["Invoice"].nunique().sort_values(
    ascending=False
).head(15)

Country
United Kingdom     23494
Germany              603
France               461
EIRE                 360
Belgium              119
Spain                105
Netherlands          101
Switzerland           74
Portugal              71
Australia             69
Italy                 55
Finland               48
Sweden                46
Norway                40
Channel Islands       33
Name: Invoice, dtype: int64

In [29]:
df["Revenue"].describe()

count    541910.000000
mean         17.987795
std         378.810474
min     -168469.600000
25%           3.400000
50%           9.750000
75%          17.400000
max      168469.600000
Name: Revenue, dtype: float64

In [30]:
df["Revenue"].sum()

np.float64(9747765.934)

In [31]:
df.groupby("Country")["Revenue"].sum().sort_values(
    ascending=False
).head(15)

Country
United Kingdom     8187806.364
Netherlands         284661.540
EIRE                263276.820
Germany             221698.210
France              197421.900
Australia           137077.270
Switzerland          56385.350
Spain                54774.580
Belgium              40910.960
Sweden               36595.910
Japan                35340.620
Norway               35163.460
Portugal             29367.020
Finland              22326.740
Channel Islands      20086.290
Name: Revenue, dtype: float64

In [32]:
df.loc[
    df["Revenue"].abs().nlargest(20).index,
    [
        "Invoice",
        "StockCode",
        "Description",
        "Quantity",
        "Price",
        "Customer ID",
        "Country",
        "Revenue"
    ]
].sort_values("Revenue")

,Invoice,StockCode,Description,Quantity,Price,Customer ID,Country,Revenue
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2.08,16446.0,United Kingdom,-168469.60
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,1.04,12346.0,United Kingdom,-77183.60
222681,C556445,M,Manual,-1,38970.00,15098.0,United Kingdom,-38970.00
524602,C580605,AMAZONFEE,AMAZON FEE,-1,17836.46,NaN,United Kingdom,-17836.46
43702,C540117,AMAZONFEE,AMAZON FEE,-1,16888.02,NaN,United Kingdom,-16888.02
43703,C540118,AMAZONFEE,AMAZON FEE,-1,16453.71,NaN,United Kingdom,-16453.71
15016,C537630,AMAZONFEE,AMAZON FEE,-1,13541.33,NaN,United Kingdom,-13541.33
16356,C537651,AMAZONFEE,AMAZON FEE,-1,13541.33,NaN,United Kingdom,-13541.33
16002,C537644,AMAZONFEE,AMAZON FEE,-1,13474.79,NaN,United Kingdom,-13474.79
524601,C580604,AMAZONFEE,AMAZON FEE,-1,11586.50,NaN,United Kingdom,-11586.50
299983,A563186,B,Adjust bad debt,1,-11062.06,NaN,United Kingdom,-11062.06
299984,A563187,B,Adjust bad debt,1,-11062.06,NaN,United Kingdom,-11062.06
422375,C573079,M,Manual,-2,4161.06,12536.0,France,-8322.12
446533,C574902,AMAZONFEE,AMAZON FEE,-1,8286.22,NaN,United Kingdom,-8286.22
173277,C551685,POST,POSTAGE,-1,8142.75,16029.0,United Kingdom,-8142.75
299982,A563185,B,Adjust bad debt,1,11062.06,NaN,United Kingdom,11062.06
15017,537632,AMAZONFEE,AMAZON FEE,1,13541.33,NaN,United Kingdom,13541.33
222671,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50,15098.0,United Kingdom,38970.00
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,12346.0,United Kingdom,77183.60
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,16446.0,United Kingdom,168469.60

In [33]:
df[df["Revenue"].abs() > 10000][
    [
        "Invoice",
        "StockCode",
        "Description",
        "Quantity",
        "Price",
        "Customer ID",
        "Country",
        "Revenue"
    ]
]

,Invoice,StockCode,Description,Quantity,Price,Customer ID,Country,Revenue
15016,C537630,AMAZONFEE,AMAZON FEE,-1,13541.33,NaN,United Kingdom,-13541.33
15017,537632,AMAZONFEE,AMAZON FEE,1,13541.33,NaN,United Kingdom,13541.33
16002,C537644,AMAZONFEE,AMAZON FEE,-1,13474.79,NaN,United Kingdom,-13474.79
16356,C537651,AMAZONFEE,AMAZON FEE,-1,13541.33,NaN,United Kingdom,-13541.33
43702,C540117,AMAZONFEE,AMAZON FEE,-1,16888.02,NaN,United Kingdom,-16888.02
43703,C540118,AMAZONFEE,AMAZON FEE,-1,16453.71,NaN,United Kingdom,-16453.71
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,12346.0,United Kingdom,77183.60
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,1.04,12346.0,United Kingdom,-77183.60
222671,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50,15098.0,United Kingdom,38970.00
222681,C556445,M,Manual,-1,38970.00,15098.0,United Kingdom,-38970.00
299982,A563185,B,Adjust bad debt,1,11062.06,NaN,United Kingdom,11062.06
299983,A563186,B,Adjust bad debt,1,-11062.06,NaN,United Kingdom,-11062.06
299984,A563187,B,Adjust bad debt,1,-11062.06,NaN,United Kingdom,-11062.06
524601,C580604,AMAZONFEE,AMAZON FEE,-1,11586.50,NaN,United Kingdom,-11586.50
524602,C580605,AMAZONFEE,AMAZON FEE,-1,17836.46,NaN,United Kingdom,-17836.46
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,16446.0,United Kingdom,168469.60
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2.08,16446.0,United Kingdom,-168469.60

Data Cleaning

In [34]:
df_clean = df.copy()

In [35]:
before = len(df_clean)

df_clean = df_clean.drop_duplicates()

after = len(df_clean)

print("Rows before:", before)
print("Rows after:", after)
print("Duplicates removed:", before - after)

Rows before: 541910
Rows after: 536642
Duplicates removed: 5268

In [36]:
df_clean.duplicated().sum()

np.int64(0)

In [37]:
# Check the special transaction types
print("Cancellations:", df_clean["Invoice"].astype(str).str.startswith("C").sum())
print("Amazon fees:", (df_clean["StockCode"].astype(str) == "AMAZONFEE").sum())
print("Manual transactions:", (df_clean["StockCode"].astype(str) == "M").sum())
print("Bad debt adjustments:", (df_clean["StockCode"].astype(str) == "B").sum())

Cancellations: 9251
Amazon fees: 34
Manual transactions: 566
Bad debt adjustments: 3

In [38]:
df_clean = df.copy()

print("Original rows:", len(df))
print("Working rows:", len(df_clean))

Original rows: 541910
Working rows: 541910

In [40]:
print("Remaining duplicates:", df_clean.duplicated().sum())

Remaining duplicates: 0

In [41]:
df_clean.dtypes

Invoice            str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
Price          float64
Customer ID    float64
Country            str
Revenue        float64
dtype: object

In [42]:
df_clean["Invoice"] = df_clean["Invoice"].astype(str)
df_clean["StockCode"] = df_clean["StockCode"].astype(str)
df_clean["Description"] = df_clean["Description"].astype("string")
df_clean["Country"] = df_clean["Country"].astype("string")

df_clean["Quantity"] = pd.to_numeric(
    df_clean["Quantity"],
    errors="coerce"
)

df_clean["Price"] = pd.to_numeric(
    df_clean["Price"],
    errors="coerce"
)

df_clean["Customer ID"] = pd.to_numeric(
    df_clean["Customer ID"],
    errors="coerce"
)

In [43]:
df_clean["InvoiceDate"] = pd.to_datetime(
    df_clean["InvoiceDate"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

In [44]:
print(df_clean["InvoiceDate"].dtype)
print(df_clean["InvoiceDate"].isna().sum())

datetime64[us]
0

In [45]:
df_clean["Year"] = df_clean["InvoiceDate"].dt.year
df_clean["Month"] = df_clean["InvoiceDate"].dt.month
df_clean["Day"] = df_clean["InvoiceDate"].dt.day
df_clean["Hour"] = df_clean["InvoiceDate"].dt.hour
df_clean["DayOfWeek"] = df_clean["InvoiceDate"].dt.day_name()

In [46]:
df_clean["Revenue"] = (
    df_clean["Quantity"] * df_clean["Price"]
)

In [47]:
df_clean["Revenue"].describe()

count    536642.000000
mean         18.123861
std         380.655908
min     -168469.600000
25%           3.750000
50%           9.870000
75%          17.400000
max      168469.600000
Name: Revenue, dtype: float64

In [48]:
def classify_transaction(row):

    invoice = str(row["Invoice"])
    stockcode = str(row["StockCode"]).upper()
    description = str(row["Description"]).upper()

    if stockcode == "AMAZONFEE":
        return "AMAZON_FEE"

    elif stockcode == "M":
        return "MANUAL_ADJUSTMENT"

    elif stockcode == "B":
        return "BAD_DEBT_ADJUSTMENT"

    elif invoice.startswith("C"):
        return "CANCELLATION"

    elif row["Quantity"] < 0:
        return "RETURN_OR_NEGATIVE_TRANSACTION"

    elif row["Price"] < 0:
        return "NEGATIVE_PRICE_ADJUSTMENT"

    elif row["Price"] == 0:
        return "ZERO_PRICE_TRANSACTION"

    else:
        return "SALE"

In [49]:
df_clean["TransactionType"] = df_clean.apply(
    classify_transaction,
    axis=1
)

In [50]:
df_clean["TransactionType"].value_counts()

TransactionType
SALE                              524559
CANCELLATION                        8975
RETURN_OR_NEGATIVE_TRANSACTION      1336
ZERO_PRICE_TRANSACTION              1168
MANUAL_ADJUSTMENT                    567
AMAZON_FEE                            34
BAD_DEBT_ADJUSTMENT                    3
Name: count, dtype: int64

In [51]:
df_clean["IsCancellation"] = (
    df_clean["Invoice"].str.startswith("C")
)

In [52]:
df_clean["IsCancellation"].value_counts()

IsCancellation
False    527391
True       9251
Name: count, dtype: int64

In [53]:
df_clean["IsNegativeQuantity"] = (
    df_clean["Quantity"] < 0
)

In [54]:
df_clean["IsNegativeQuantity"].value_counts()

IsNegativeQuantity
False    526055
True      10587
Name: count, dtype: int64

In [55]:
df_clean["IsZeroPrice"] = (
    df_clean["Price"] == 0
)

In [56]:
df_clean["IsZeroPrice"].value_counts()

IsZeroPrice
False    534132
True       2510
Name: count, dtype: int64

In [57]:
missing = pd.DataFrame({
    "MissingCount": df_clean.isna().sum(),
    "MissingPercentage": (
        df_clean.isna().mean() * 100
    ).round(2)
})

print(missing)

                    MissingCount  MissingPercentage
Invoice                        0               0.00
StockCode                      0               0.00
Description                 1454               0.27
Quantity                       0               0.00
InvoiceDate                    0               0.00
Price                          0               0.00
Customer ID               135037              25.16
Country                        0               0.00
Revenue                        0               0.00
Year                           0               0.00
Month                          0               0.00
Day                            0               0.00
Hour                           0               0.00
DayOfWeek                      0               0.00
TransactionType                0               0.00
IsCancellation                 0               0.00
IsNegativeQuantity             0               0.00
IsZeroPrice                    0               0.00

In [58]:
print(
    "Missing descriptions:",
    df_clean["Description"].isna().sum()
)

Missing descriptions: 1454

In [59]:
print(
    df_clean.loc[
        df_clean["Description"].isna(),
        "TransactionType"
    ].value_counts()
)

TransactionType
RETURN_OR_NEGATIVE_TRANSACTION    862
ZERO_PRICE_TRANSACTION            592
Name: count, dtype: int64

In [61]:
print("Negative prices:",
    (df_clean["Price"] < 0).sum())

print("Zero prices:",
    (df_clean["Price"] == 0).sum())

Negative prices: 2
Zero prices: 2510

In [62]:
sales_df = df_clean[
    (df_clean["TransactionType"] == "SALE")
    &
    (df_clean["Quantity"] > 0)
    &
    (df_clean["Price"] > 0)
].copy()

In [63]:
print("Sales rows:", len(sales_df))
print("Sales revenue:", sales_df["Revenue"].sum())

Sales rows: 524559
Sales revenue: 10539552.833999999

In [64]:
returns_df = df_clean[
    df_clean["TransactionType"] == "CANCELLATION"
].copy()

In [65]:
print("Cancellation rows:", len(returns_df))
print(
    "Cancellation value:",
    returns_df["Revenue"].sum()
)

Cancellation rows: 8975
Cancellation value: -511913.67999999993

In [66]:
product_transactions = df_clean[
    ~df_clean["TransactionType"].isin([
        "AMAZON_FEE",
        "MANUAL_ADJUSTMENT",
        "BAD_DEBT_ADJUSTMENT"
    ])
].copy()

In [67]:
net_revenue = product_transactions["Revenue"].sum()

print("Net product revenue:", net_revenue)

Net product revenue: 10027639.154

In [68]:
sales_df["Revenue"].abs().nlargest(20)

540421    168469.60
61619      77183.60
222671     38970.00
173382      8142.75
348325      7144.72
52711       6539.40
160546      6539.40
421601      4992.00
52709       4921.50
467804      4781.60
160542      4632.00
52772       4522.50
297725      4505.17
244419      4401.00
160544      4254.50
291249      4176.00
52134       4121.64
533812      3861.00
16438       3828.00
348319      3825.36
Name: Revenue, dtype: float64

In [69]:
sales_df.loc[
    sales_df["Revenue"].abs().nlargest(20).index,
    [
        "Invoice",
        "StockCode",
        "Description",
        "Quantity",
        "Price",
        "Customer ID",
        "Country",
        "Revenue"
    ]
]

,Invoice,StockCode,Description,Quantity,Price,Customer ID,Country,Revenue
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,16446.0,United Kingdom,168469.60
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,12346.0,United Kingdom,77183.60
222671,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50,15098.0,United Kingdom,38970.00
173382,551697,POST,POSTAGE,1,8142.75,16029.0,United Kingdom,8142.75
348325,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,5.06,17450.0,United Kingdom,7144.72
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749.0,United Kingdom,6539.40
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749.0,United Kingdom,6539.40
421601,573003,23084,RABBIT NIGHT LIGHT,2400,2.08,14646.0,Netherlands,4992.00
52709,540815,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,2.55,15749.0,United Kingdom,4921.50
467804,576365,22086,PAPER CHAIN KIT 50'S CHRISTMAS,688,6.95,NaN,United Kingdom,4781.60
160542,550461,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1930,2.40,15749.0,United Kingdom,4632.00
52772,540818,48185,DOORMAT FAIRY CAKE,670,6.75,15749.0,United Kingdom,4522.50
297725,562955,DOT,DOTCOM POSTAGE,1,4505.17,NaN,United Kingdom,4505.17
244419,558526,23173,REGENCY TEAPOT ROSES,540,8.15,17949.0,United Kingdom,4401.00
160544,550461,48185,DOORMAT FAIRY CAKE,670,6.35,15749.0,United Kingdom,4254.50
291249,562439,84879,ASSORTED COLOUR BIRD ORNAMENT,2880,1.45,12931.0,United Kingdom,4176.00
52134,540689,22470,HEART OF WICKER LARGE,1284,3.21,17450.0,United Kingdom,4121.64
533812,581115,22413,METAL SIGN TAKE IT OR LEAVE IT,1404,2.75,15195.0,United Kingdom,3861.00
16438,537659,21623,VINTAGE UNION JACK MEMOBOARD,600,6.38,18102.0,United Kingdom,3828.00
348319,567423,23113,PANTRY CHOPPING BOARD,756,5.06,17450.0,United Kingdom,3825.36

In [70]:
customer_df = sales_df[
    sales_df["Customer ID"].notna()
].copy()

In [71]:
print("Rows with customer IDs:", len(customer_df))
print(
    "Unique customers:",
    customer_df["Customer ID"].nunique()
)

Rows with customer IDs: 392414
Unique customers: 4335

In [72]:
product_df = sales_df[
    sales_df["StockCode"].notna()
].copy()

In [73]:
print("===== FINAL DATA QUALITY =====")

print("Rows:", len(df_clean))
print("Columns:", len(df_clean.columns))

print(
    "Duplicate rows:",
    df_clean.duplicated().sum()
)

print(
    "Missing Invoice:",
    df_clean["Invoice"].isna().sum()
)

print(
    "Missing StockCode:",
    df_clean["StockCode"].isna().sum()
)

print(
    "Missing Quantity:",
    df_clean["Quantity"].isna().sum()
)

print(
    "Missing Price:",
    df_clean["Price"].isna().sum()
)

print(
    "Missing Customer ID:",
    df_clean["Customer ID"].isna().sum()
)

print(
    "Missing Description:",
    df_clean["Description"].isna().sum()
)

===== FINAL DATA QUALITY =====
Rows: 536642
Columns: 18
Duplicate rows: 0
Missing Invoice: 0
Missing StockCode: 0
Missing Quantity: 0
Missing Price: 0
Missing Customer ID: 135037
Missing Description: 1454

In [77]:
df_clean.to_csv("../data/clean_transactions.csv", index=False)

In [78]:
clean_check = pd.read_csv("../data/clean_transactions.csv")

print(clean_check.shape)
print(clean_check.columns.tolist())

(536642, 18)
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country', 'Revenue', 'Year', 'Month', 'Day', 'Hour', 'DayOfWeek', 'TransactionType', 'IsCancellation', 'IsNegativeQuantity', 'IsZeroPrice']